Repository openrewrite/rewrite-static-analysis, pull requests merged in 2023-08, with the labels that each got.

#148 `ReplaceLambdaWithMethodReference` should not replace ambiguous references
  src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
Labels: bug

#147 Do not remove unused variables with constructor calls
  src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java
Labels: bug

#153 RemoveUnusedLocalVariables fails inside case blocks (test)
  src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java
Labels: bug

#146 MinimumSwitchCases should add Enum import when necessary
  src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
  src/test/java/org/openrewrite/staticanalysis/MinimumSwitchCasesTest.java
Labels: bug

#155 Extend SimplifyBooleanExpressionVisitor
  src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpression.java
Labels: enhancement

#93 Ternary operator should not be nested
  src/main/java/org/openrewrite/staticanalysis/TernaryOperatorsShouldNotBeNested.java
  src/test/java/org/openrewrite/staticanalysis/TernaryOperatorsShouldNotBeNestedTest.java
Labels: recipe
