Repository openrewrite/rewrite-static-analysis, pull requests merged in 2023-06, with the labels that each got.

#120 Remove blank JavaDoc blocks after RemoveJavaDocAuthorTag
  src/main/java/org/openrewrite/staticanalysis/RemoveJavaDocAuthorTag.java
  src/test/java/org/openrewrite/staticanalysis/RemoveJavaDocAuthorTagTest.java
Labels: enhancement

#124 new recipe that changes .equals() to .contentEquals() when comparing …
  gradle/licenseHeader.txt
  src/main/java/org/openrewrite/staticanalysis/EqualsToContentEquals.java
  src/test/java/org/openrewrite/staticanalysis/EqualsToContentEqualsTest.java
Labels: recipe

#128 Remove hashCode calls on arrays
  src/main/java/org/openrewrite/staticanalysis/RemoveHashCodeCallsFromArrayInstances.java
  src/test/java/org/openrewrite/staticanalysis/RemoveHashCodeCallsFromArrayInstancesTest.java
Labels: recipe

#126 Alek/remove to string calls from array instances
  src/main/java/org/openrewrite/staticanalysis/RemoveToStringCallsFromArrayInstances.java
  src/test/java/org/openrewrite/staticanalysis/EqualsToContentEqualsTest.java
  src/test/java/org/openrewrite/staticanalysis/RemoveToStringCallsFromArrayInstancesTest.java
Labels: recipe

#131 Better type attribution for `ReplaceLambdaWithMethodReference`
  src/main/java/org/openrewrite/staticanalysis/JavaElementFactory.java
  src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
  src/test/java/org/openrewrite/staticanalysis/JavaElementFactoryTest.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
Labels: enhancement

#132 `ReplaceLambdaWithMethodReference` should not replace lambda supplier of method reference with method reference
  src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
Labels: bug
