Repository openrewrite/rewrite-static-analysis, pull requests merged in 2024-02, with the labels that each got.

#252 Add BigDecimalDoubleConstructor Recipe
  src/main/java/org/openrewrite/staticanalysis/BigDecimalDoubleConstructor.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/BigDecimalDoubleConstructorTest.java
Labels: bug, recipe

#240 ReplaceLambdaWithMethodReference skip parameterized method return types
  src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
Labels: bug

#248 Fully remove part provider and last remaining references
  src/main/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithString.java
Labels: enhancement

#261 Do not escape newline in FixStringFormatExpressions
  src/main/java/org/openrewrite/staticanalysis/FixStringFormatExpressions.java
  src/test/java/org/openrewrite/staticanalysis/FixStringFormatExpressionsTest.java
Labels: bug
