Repository openrewrite/rewrite-static-analysis, pull requests merged in 2024-12, with the labels that each got.

#401 Prove C# support for ExplicitInitialization recipe
  src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
  src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
  src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java
  src/test/java/org/openrewrite/staticanalysis/charp/ExplicitInitializationVisitorCsharpTest.java
  src/test/java/org/openrewrite/staticanalysis/charp/JavaToCsharp.java
Labels: recipe

#402 Move `verifyCsharpImplicitThrow` to own Csharp test class
  src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
  src/test/java/org/openrewrite/staticanalysis/charp/CatchClauseOnlyRethrowsCsharpTest.java
Labels: recipe

#397 Adjust `MethodNameCasing` to work with C#
  src/main/java/org/openrewrite/staticanalysis/MethodNameCasing.java
Labels: enhancement, recipe

#405 Disable `MinimumSwitchCases` for C#
  src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
Labels: enhancement

#251 Add URLEqualHashCode Recipe
  src/main/java/org/openrewrite/staticanalysis/URLEqualsHashCode.java
  src/test/java/org/openrewrite/staticanalysis/URLEqualsHashCodeTest.java
Labels: recipe

#404 `NullableOnMethodReturnType` should not change identity on package private methods
  src/main/java/org/openrewrite/staticanalysis/NullableOnMethodReturnType.java
  src/test/java/org/openrewrite/staticanalysis/NullableOnMethodReturnTypeTest.java
Labels: bug

#415 `UseLambdaForFunctionalInterface` recipe should not convert when code uses a static field from enum constructor
  src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java
  src/test/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterfaceTest.java
Labels: bug, recipe
