Repository openrewrite/rewrite-static-analysis, pull requests merged in 2024-01, with the labels that each got.

#231 Simplify Ternary expressions [#203]
  build.gradle.kts
  src/main/java/org/openrewrite/staticanalysis/SimplifyTernary.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/SimplifyTernaryTest.java
Labels: recipe

#241 feature(LambdaBlockToExpression): convert lambda with method invocation as well
  src/main/java/org/openrewrite/staticanalysis/LambdaBlockToExpression.java
  src/test/java/org/openrewrite/staticanalysis/LambdaBlockToExpressionTest.java
  src/test/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterfaceTest.java
Labels: enhancement

#244 #242 Fix remove unused private fields
  src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFields.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFieldsTest.java
Labels: bug, enhancement
