Repository openrewrite/rewrite-static-analysis, pull requests merged in 2024-11, with the labels that each got.

#388 Unnecessary `return` as last statement in `void` method
  src/main/java/org/openrewrite/staticanalysis/UnnecessaryReturnAsLastStatement.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/UnnecessaryReturnAsLastStatementTest.java
Labels: recipe

#395 Adjust `CatchClauseOnlyRethrows` to work with C#
  src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
  src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
  src/test/java/org/openrewrite/staticanalysis/JavaToCsharp.java
Labels: enhancement, recipe

#396 Improve recipes and excluded them from C# codebase if needed
  src/main/java/org/openrewrite/staticanalysis/AtomicPrimitiveEqualsUsesGet.java
  src/main/java/org/openrewrite/staticanalysis/CaseInsensitiveComparisonsDoNotChangeCase.java
  src/main/java/org/openrewrite/staticanalysis/CovariantEquals.java
  src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNull.java
  src/main/java/org/openrewrite/staticanalysis/ExternalizableHasNoArgsConstructor.java
  src/main/java/org/openrewrite/staticanalysis/FixStringFormatExpressions.java
  src/main/java/org/openrewrite/staticanalysis/IndexOfChecksShouldUseAStartPosition.java
  src/main/java/org/openrewrite/staticanalysis/IndexOfReplaceableByContains.java
  src/main/java/org/openrewrite/staticanalysis/IndexOfShouldNotCompareGreaterThanZero.java
  src/main/java/org/openrewrite/staticanalysis/NestedEnumsAreNotStatic.java
  src/main/java/org/openrewrite/staticanalysis/NewStringBuilderBufferWithCharArgument.java
  src/main/java/org/openrewrite/staticanalysis/NoFinalizer.java
  src/main/java/org/openrewrite/staticanalysis/NoValueOfOnStringType.java
  src/main/java/org/openrewrite/staticanalysis/ObjectFinalizeCallsSuper.java
  src/main/java/org/openrewrite/staticanalysis/PrimitiveWrapperClassConstructorToValueOf.java
  src/main/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCase.java
  src/main/java/org/openrewrite/staticanalysis/RenamePrivateFieldsToCamelCase.java
  src/main/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithString.java
  src/main/java/org/openrewrite/staticanalysis/StringLiteralEquality.java
  src/main/java/org/openrewrite/staticanalysis/UseJavaStyleArrayDeclarations.java
  src/main/java/org/openrewrite/staticanalysis/WriteOctalValuesAsDecimal.java
  src/main/java/org/openrewrite/staticanalysis/csharp/CSharpFileChecker.java
Labels: bug

#398 `EqualsAvoidsNull` should flip arguments for constants
  src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNull.java
  src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
  src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
Labels: enhancement
