Repository openrewrite/rewrite-static-analysis, pull requests merged in 2024-10, with the labels that each got.

#348 Fix: `CatchClauseOnlyRethrows` does not handle multi catch correctly
  src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
  src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
Labels: bug

#368 address: LiteralsFirstInComparisons PMD rule
  src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
  src/main/java/org/openrewrite/staticanalysis/UseStringReplace.java
  src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
Labels: enhancement

#355 Fix `CatchCauseOnlyRethrows` onlyRethrows check for multi catch statements
  src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
  src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
Labels: bug

#375 Setting the maximum generated variable length to 40
  src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiteralsTest.java
Labels: enhancement

#378 Allow removal of unused local variables with side effects in initializer
  src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java
Labels: enhancement

#364 Add `AnnotateNullableMethods` recipe
  src/main/java/org/openrewrite/staticanalysis/AnnotateNullableMethods.java
  src/test/java/org/openrewrite/staticanalysis/AnnotateNullableMethodsTest.java
Labels: recipe

#258 Add `BufferedWriterCreation` recipe
  src/main/java/org/openrewrite/staticanalysis/BufferedWriterCreation.java
  src/main/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecution.java
  src/test/java/org/openrewrite/staticanalysis/BufferedWriterCreationTest.java
Labels: enhancement, recipe

#381 Add recipe `ReplaceClassIsInstanceWithInstanceof` for SonarQube RSPEC-6202
  src/main/java/org/openrewrite/staticanalysis/ReplaceClassIsInstanceWithInstanceof.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/ReplaceClassIsInstanceWithInstanceofTest.java
Labels: recipe
