Repository openrewrite/rewrite-static-analysis, pull requests merged in 2025-04, with the labels that each got.

#492 Fix missing constructor argument issue
  src/main/java/org/openrewrite/staticanalysis/NoDoubleBraceInitialization.java
  src/test/java/org/openrewrite/staticanalysis/NoDoubleBraceInitializationTest.java
Labels: recipe

#489 Fix several issues in InstanceOfPatternMatch
  src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
  src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java
Labels: bug

#501 Revert option for literal visiting in ChangePackage/ChangeType
  src/main/java/org/openrewrite/staticanalysis/LowercasePackage.java
  src/main/java/org/openrewrite/staticanalysis/ReplaceStackWithDeque.java
Labels: bug

#505 Avoid double negation in SimplifyBooleanReturn
  src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanReturn.java
  src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanReturnTest.java
Labels: bug, good first issue

#468 Fix RemoveUnusedPrivateMethods `org.opentest4j.AssertionFailedError`
  src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethods.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethodsTest.java
Labels: enhancement

#517 UseCollectionInterfaces updates methodInvovations type info to enable import removal
  src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
  src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java
Labels: bug, recipe

#520 DefaultComesLast should correctly support fall through cases
  src/main/java/org/openrewrite/staticanalysis/DefaultComesLastVisitor.java
  src/test/java/org/openrewrite/staticanalysis/DefaultComesLastTest.java
Labels: bug, recipe

#522 Enhance ExplicitInitialization to handle anonymous classes
  src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
  src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java
Labels: enhancement

#530 fix: use box for primitives when rewriting `instanceof` (#528)
  src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
  src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java
Labels: bug, recipe
