Repository openrewrite/rewrite-static-analysis, pull requests merged in 2025-05, with the labels that each got.

#541 Enable custom Serial Version UID
  src/main/java/org/openrewrite/staticanalysis/AddSerialVersionUidToSerializable.java
  src/test/java/org/openrewrite/staticanalysis/AddSerialAnnotationToSerialVersionUIDTest.java
  src/test/java/org/openrewrite/staticanalysis/AddSerialVersionUidToSerializableTest.java
  src/test/java/org/openrewrite/staticanalysis/HiddenFieldTest.java
Labels: enhancement, recipe

#518 Fix Comment handling in NeedsBraces
  src/main/java/org/openrewrite/staticanalysis/NeedBraces.java
  src/test/java/org/openrewrite/staticanalysis/NeedBracesTest.java
Labels: bug

#542 CustomImportOrder recipe
  src/main/java/org/openrewrite/staticanalysis/CustomImportOrder.java
  src/main/java/org/openrewrite/staticanalysis/CustomImportOrderVisitor.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/main/resources/META-INF/rewrite/static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/CustomImportOrderRecipeTest.java
Labels: recipe

#547 Handle static method calls when removing unnecessary explicit type arguments.
  src/main/java/org/openrewrite/staticanalysis/UnnecessaryExplicitTypeArguments.java
  src/test/java/org/openrewrite/staticanalysis/UnnecessaryExplicitTypeArgumentsTest.java
Labels: bug, recipe

#546 SimplifyConstantIfBranchExecution leaves unreachable code
  src/main/java/org/openrewrite/staticanalysis/RemoveUnneededBlock.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnneededBlockTest.java
  src/test/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecutionTest.java
Labels: bug

#548 Configurable NoFinalizedLocalVariables for excluding methods parameters
  src/main/java/org/openrewrite/staticanalysis/NoFinalizedLocalVariables.java
  src/test/java/org/openrewrite/staticanalysis/NoFinalizedLocalVariablesTest.java
Labels: enhancement

#549 TestNG matching for RemoveUnneededAssertion
  build.gradle.kts
  src/main/java/org/openrewrite/staticanalysis/RemoveUnneededAssertion.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnneededAssertionTest.java
Labels: enhancement, good first issue

#539 Run test methods in parallel but classes sequential
  src/main/resources/junit-platform.properties
Labels: enhancement

#563 Enhance RemoveUnusedLocalVariables to support filtering by type
  src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
  src/main/resources/META-INF/rewrite/examples.yml
  src/test/java/org/openrewrite/staticanalysis/MinimumSwitchCasesTest.java
  src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
Labels: enhancement
