Repository openrewrite/rewrite-static-analysis, pull requests merged in 2025-08, with the labels that each got.

#706 Add `RemoveRedundantNullCheckBeforeLiteralEquals`
  src/main/java/org/openrewrite/staticanalysis/RemoveRedundantNullCheckBeforeLiteralEquals.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/RemoveRedundantNullCheckBeforeLiteralEqualsTest.java
Labels: recipe

#709 fix: Enhanced UseCollectionInterfaces to prevent conversions when non interface methods are used
  src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
  src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java
Labels: bug, enhancement

#711 Improve support method invocations for `RemoveRedundantTypeCast`
  src/main/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCast.java
  src/test/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCastTest.java
Labels: enhancement, recipe

#723 Fix ReplaceLambdaWithMethodReference to not replace lambdas inside anonymous inner classes
  src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
Labels: bug
