Repository openrewrite/rewrite-static-analysis, pull requests merged in 2025-07, with the labels that each got.

#625 Issue #622: precompile regexes in FixStringFormatExpressions.java and…
  src/main/java/org/openrewrite/staticanalysis/FixStringFormatExpressions.java
  src/main/java/org/openrewrite/staticanalysis/MaskCreditCardNumbers.java
Labels: enhancement

#633 Simplify `Arrays.asList` with new array argument
  .claude/settings.local.json
  src/main/java/org/openrewrite/staticanalysis/SimplifyArraysAsList.java
  src/main/resources/META-INF/rewrite/common-static-analysis.yml
  src/test/java/org/openrewrite/staticanalysis/SimplifyArraysAsListTest.java
Labels: recipe

#638 Fix `UnnecessaryCatch` Recipe Multi-Catch Handling
  src/main/java/org/openrewrite/staticanalysis/UnnecessaryCatch.java
  src/test/java/org/openrewrite/staticanalysis/UnnecessaryCatchTest.java
Labels: bug, recipe

#495 RemoveRedundantTypeCast should not remove required downcast
  src/main/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCast.java
  src/test/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCastTest.java
Labels: bug, good first issue, recipe

#675 Keep indentation when running `FinalizePrivateFields`
  src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
  src/test/java/org/openrewrite/staticanalysis/FinalizePrivateFieldsTest.java
Labels: bug
