Repository openrewrite/rewrite-static-analysis, pull requests merged in 2025-01, with the labels that each got.

#438 Guard against missing Cs class now that dependency is provided
  src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
  src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
  src/main/java/org/openrewrite/staticanalysis/csharp/CSharpFileChecker.java
  src/main/java/org/openrewrite/staticanalysis/csharp/package-info.java
Labels: bug

#385 `ReplaceDuplicateStringLiterals` throws NPE from 1.19.0+ #384
  src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
  src/test/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiteralsTest.java
Labels: bug

#439 Don't remove necessary whitespace in EqualsAvoidNull
  src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
  src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
Labels: bug

#444 Skip constructors in `UnnecessaryThrows` for now
  src/main/java/org/openrewrite/staticanalysis/UnnecessaryThrows.java
  src/test/java/org/openrewrite/staticanalysis/UnnecessaryThrowsTest.java
Labels: bug

#451 feat: prevent UnnecessaryCatch from removing `catch (Throwable t)`
  src/main/java/org/openrewrite/staticanalysis/UnnecessaryCatch.java
  src/test/java/org/openrewrite/staticanalysis/UnnecessaryCatchTest.java
Labels: bug

#454 Expand `RemoveExtraSemicolons` description
  src/main/java/org/openrewrite/staticanalysis/RemoveExtraSemicolons.java
  src/test/java/org/openrewrite/staticanalysis/AbstractClassPublicConstructorTest.java
  src/test/java/org/openrewrite/staticanalysis/RemoveExtraSemicolonsTest.java
Labels: documentation, enhancement

#455 Improve CatchClauseOnlyRethrows to support MultiCatch completely
  src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
  src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
Labels: bug, recipe
